# Kitty Configuration - Hayase Yuuka / Caelestia Theme

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

# Window layout
window_padding_width 12
hide_window_decorations yes
confirm_os_window_close 0

# Transparency
background_opacity 0.85
dynamic_background_opacity yes

# Colors
foreground              #e5e1e7
background              #131317
selection_foreground    #131317
selection_background    #bfc1ff

# Cursor
cursor                  #bfc1ff
cursor_text_color       #131317
cursor_shape            beam

# URL underline color when hovering with mouse
url_color               #aeb8ff

# Kitty window border colors
active_border_color     #6f72ac
inactive_border_color   #39393d
bell_border_color       #ffb4ab

# Tab bar colors
active_tab_foreground   #131317
active_tab_background   #bfc1ff
inactive_tab_foreground #e5e1e7
inactive_tab_background #1b1b1f
tab_bar_background      #131317

# The 16 terminal colors
# normal
color0 #353434
color1 #a875ff
color2 #44def5
color3 #ffdcf2
color4 #97aad7
color5 #b29feb
color6 #9dceff
color7 #e8d3de

# bright
color8 #ac9fa9
color9 #bd95ff
color10 #89ecff
color11 #fff0f6
color12 #b4c1dc
color13 #c8b5f5
color14 #bae0ff
color15 #ffffff
