# Hyprlock Configuration - Hayase Yuuka Theme

background {
    monitor =
    path = ~/wallpapers/wallpaper.png
    color = rgba(19, 19, 23, 1.0) # base
    blur_passes = 2
    blur_size = 3
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(111, 114, 172) # primaryContainer
    inner_color = rgb(19, 19, 23) # surface
    font_color = rgb(229, 225, 231) # onSurface
    fade_on_empty = true
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(191, 193, 255) # primary
    font_size = 75
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi there, $USER
    color = rgb(229, 225, 231) # onSurface
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
